\chapter{Background}
\label{ch:background}

\section{How genome changes}
\subsection{Cross-over}
\subsection{Gene conversion}
\subsection{Point mutations}
\subsection{Structural variants}
\subsubsection{Small (indels)}
\subsubsection{Large (fusions, NAHR)}
\subsubsection{Chromosomal changes}

\section{Rates}

\section{Factors influencing}
\subsection{Replication time}
\subsection{Mat/pat age effects}
\subsection{Biases/locality}

\section{Known events in species}
\subsection{P.f.}
\subsection{Human}
\subsection{Chimp}
\subsection{Others}
